### ISSUE TITLE
I don't get it

### ISSUE THREAD

**Issue by JesseTG** [bjorn/bitcoin-icecream#3]
What is the purpose of this repo, exactly?  Where I can buy you ice cream?  Not knocking you, just curious.  Is this an inside joke?

**Comment by bjorn** [comment]
Back in 2014, my employer stopped ordering new ice-cream because apparently some people were taking ice-cream without going to the reception to pay for it. Since we still wanted to eat ice-cream, me and a colleague, @Domderon, starting buying ice-cream and putting it in the freezer. To allow others to also eat ice-cream, we set up this website so that they could pay for it easily with their phones.

The hope was that with cheaper ice-cream and an easier payment method, there would be no thieves this time, but in the end it turned out there still went a large amount of ice-cream missing. Eventually, our employer decided to order ice-cream again, but the freezer was locked so that those who wanted to get some first had to go get the key. That probably averted the ice-cream thieves, but I'm positive it also caused a lot less ice-cream to be eaten.

The purpose of this repository was just to allow me and my colleague to both make updates to the available ice-cream, their price and the destination Bitcoin address. Different addresses were used for each type of ice-cream so that we would know when a certain type was about to run out.

The repository can be used as a starting point for anybody else who wants to start selling something for Bitcoin. Though it can only be used in an environment of trust, unless you're sitting next to the goods you're selling.

**Comment by JesseTG** [comment]
Huh.  Interesting.  Thanks for the story!
